name: CI/CD to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: tododevopsacr.azurecr.io
  RESOURCE_GROUP: todo-devops-rg
  AKS_CLUSTER_NAME: tododevopsaks
  IMAGE_NAME: todo-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Image
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.32.0'

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }} --overwrite-existing

    - name: Deploy to AKS
      run: |
        # Update deployment with new image
        sed -i 's|<ACR_LOGIN_SERVER>|${{ env.ACR_LOGIN_SERVER }}|g' kubernetes/deployment.yaml
        sed -i 's|<BUILD_ID>|${{ github.sha }}|g' kubernetes/deployment.yaml

        kubectl apply -f kubernetes/
        kubectl set image deployment/todo-app-deployment todo-app-container=${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        kubectl rollout status deployment/todo-app-deployment
